---
development:
  dialect: postgres
  database: {{ envOr "DATABASE_NAME" "gocard_development" }}
  user: {{ envOr "DATABASE_USER" "postgres" }}
  password: {{ envOr "DATABASE_PASSWORD" "password" }}
  host: {{ envOr "DATABASE_HOST" "localhost" }}
  port: {{ envOr "DATABASE_PORT" "5432" }}
  pool: 5

test:
  dialect: postgres
  database: gocard_test
  user: {{ envOr "DATABASE_USER" "postgres" }}
  password: {{ envOr "DATABASE_PASSWORD" "password" }}
  host: {{ envOr "DATABASE_HOST" "localhost" }}
  port: {{ envOr "DATABASE_PORT" "5432" }}
  pool: 5

# staging:
#   url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gocard_staging?sslmode=disable"}}

# production:
#   url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/gocard_production?sslmode=disable"}}
