version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/src/work
    env_file:
      - .env
  database:
    image: postgres:11.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  postgresdata: {}
